tasks:
  - before: |
      export XDG_DATA_HOME=/workspace/.local/share
      export XDG_CONFIG_HOME=/workspace/.local/config
      export XDG_STATE_HOME=/workspace/.local/state
      export XDG_CACHE_HOME=/workspace/.cache
      export STACK_ROOT=/home/gitpod/.stack
  
      export GHCUP_INSTALL_BASE_PREFIX=/workspace
      export BOOTSTRAP_HASKELL_NONINTERACTIVE=1
      export BOOTSTRAP_HASKELL_MINIMAL=1
      curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
      /workspace/.ghcup/bin/ghcup install stack
      /workspace/.ghcup/bin/ghcup install hls
      
      pushd /usr/local/bin
      sudo ln -s /workspace/.ghcup/bin/* /usr/local/bin
      popd
    
      stack update

vscode:
  extensions:
    - haskell.haskell